### ISSUE TITLE
[newrelic-logging] Update parsers with fluentbits parsers.conf

### ISSUE THREAD

**Issue by Voziv** [newrelic/helm-charts#113]
**Is your feature request related to a problem? Please describe.**

The [fluentbit parsers.conf](https://github.com/fluent/fluent-bit/blob/master/conf/parsers.conf) includes additional parsers for apache and nginx. I'd like to either update the chart with these, or add the ability to specify custom parsers which would be covered by #75  I believe.

**Describe the solution you'd like**

The parsers.conf to be updated, or the ability to specify custom parsers

**Describe alternatives you've considered**

- Patching the configmap, however we use Infrastructure as Code via ArgoCD which makes this task much harder.
- Using a forked branch. We're doing this now but this means our deployment will likely fall out of date. Would much prefer an upstream solution.

**Additional context**

I can make a PR for this change. I just need to know whether we'd like to include more parsers by default or omit the parsers and have users specify their own custom ones instead.

**Comment by jsubirat** [comment]
Hi @Voziv , we currently just include the necessary parsers to parse logs when using the Docker interface and the CRI interface. 

Our DaemonSet collects all the logs emitted by all the pods running in each physical host, without distinguishing them by pod. In order to use the `apache` or `nginx` parsers, you'd need to have a way to say "the logs from this particular pod are of type 'apache'". Is this something you do in your fork? Could you provide an example?

Thanks.
