### ISSUE TITLE
[nri-bundle-5.0.25][newrelic-logging] log parser causing noisy warning in logs with  stderr F ...

### ISSUE THREAD

**Issue by sawlemon** [newrelic/helm-charts#1146]
**Bug description**

After upgrading the helm chart nri-bundle-5.0.25 there's lots of warning logs that accumulates to terrabytes of data which all have the pattern  `stderr F {"level":"warn","service":"<service-name>","code":2002 ...}

**Version of Helm and Kubernetes**

Kubernetes version 1.26 

**Which chart?**

nri-bundle-5.0.25 newrelic-logging chart

only difference notable is from the file charts/newrelic-logging/templates/daemonset.yaml previous LOG_PARSER value was just `cri` now it's `cri,docker`

CRI parsing was already enabled but setting `.Values.fluentBit.criEnabled` to true  before the upgrade and the logs were as expected.

**Comment by jsubirat** [comment]
Hi @sawlemon  , thank you for informing us of this. Are you perhaps overriding the `fluentBit.config.inputs` value in `values.yml`? The `INPUT` block that we now generate use the `multiline.parser` instead of `parser`, which accepts multiple parsers and attempts each one in order. This ensures that the parsing is done even if the value of `fluentBit.criEnabled` is wrong. But if you override the `fluentBit.config.inputs` block and are still using `parser` instead of `multiline.parser`, you'll face the problem you described in the ticket.

**Comment by jsubirat** [comment]
Hi @sawlemon , we proceed to close this ticket due to inactivity. Please come back to us if you experience any other issue. Thanks a lot for your feedback!
