### ISSUE TITLE
[newrelic-infrastructure] Why does the cluster role require get permission for secrets?

### ISSUE THREAD

**Issue by jasonmcboyd** [newrelic/helm-charts#128]
**Bug description**

This is a question more than a bug report or feature request. I noticed that the [cluster role](https://github.com/newrelic/helm-charts/blob/master/charts/newrelic-infrastructure/templates/clusterrole.yaml) for the network-infrastructure chart is granting get permission to all secrets in the cluster. I'm wondering what the purpose is and if it's necessary grant such broad access to secrets.

**Comment by paologallinaharbur** [comment]
Hello @jasonmcboyd,
I understand the concern, we are double-checking if we can drop some of these broad permissions.

**Comment by paologallinaharbur** [comment]
Hello again, we checked and the permission is needed in order to fetch the secret containing ETCD TLS in order to set up the MTLS for ETCD control plane monitoring.

Usually this secret it is stored in a different namespace and this is why the broad access is needed

Documentation -> https://docs.newrelic.com/docs/integrations/kubernetes-integration/installation/configure-control-plane-monitoring#etcd

Code that access the secret in nri-kubernetes -> https://github.com/newrelic/nri-kubernetes/blob/a376f16025d0096e458a24db62c365e9a01eb491/src/controlplane/client/discovery.go#L108

---

Do you have further questions regarding permissions and why they are needed?

**Comment by paologallinaharbur** [comment]
Closing for now
