### ISSUE TITLE
[newrelic-logging] installation is bumpy

### ISSUE THREAD

**Issue by kaizer113** [newrelic/helm-charts#136]
a few things:
- the memory resources allocated are too slim, these containers kept getting OOM killed on cluster with low activity
          resources:
            limits:
              cpu: 500m
              memory: 128Mi

- on OpenShift 4.4 we get errors using the hostPath definition, then errors accessing the volumes
we had to add
securityContext:
  privileged: true
and 
oc adm policy add-scc-to-user privileged system:serviceaccount:my_namespace:newrelic-logging

- to use a proxy, we had to use an environment variable 
"http_proxy"   and this is not documented

**Comment by jsubirat** [comment]
Hi @kaizer113 ,

From our experience, the current memory allocation has proved to work in many user environments, some of them with high log activity, without issues. It is possible, though, that by the time this issue was originally written we had not placed [this memory limitation in the INPUT plugin](https://github.com/newrelic/helm-charts/blob/master/charts/newrelic-logging/values.yaml#L67). Can you please confirm whether you're still observing these OOM killed errors?

Can you please follow [this documentation](https://docs.newrelic.com/docs/kubernetes-pixie/kubernetes-integration/installation/kubernetes-integration-install-configure/#install-openshift-container-platform) to install to OpenShift? It should fix your problem. Can you please confirm whether it works for you?

The proxy support has now been documented here: https://github.com/newrelic/helm-charts/tree/master/charts/newrelic-logging#proxy-support

Best regards,

Josep
