### ISSUE TITLE
[nri-bundle] Can't find the release 1.9.2

### ISSUE THREAD

**Issue by ahmad-hamade** [newrelic/helm-charts#172]
**Bug description**

Running helm repo add, refresh and find returning only 1.9.1 where 1.9.2 is the latest version

**Which chart?**

newrelic/nri-bundle

**Comment by paologallinaharbur** [comment]
Hello @ahmad-hamade first of all thank for noticing this issue. 

This is the second time that happened, I believe that the root cause is that a dependency has been updated to the same version in two different PRs:

 - https://github.com/newrelic/helm-charts/pull/129/files
 - https://github.com/newrelic/helm-charts/pull/123/files

This caused the second Release to fail and the bundle release to fail trying to push a new chart to the same release.

**In order to make sure this does not happen in the future** I added a branch protection to enforce that when merging the branch is update with master and the lint and test are run in the correct way

**Comment by paologallinaharbur** [comment]
In the meanwhile I released again nri-bundle with new features, not it is available the `1.10.0`

**Comment by ahmad-hamade** [comment]
Thanks @paologallinaharbur.
