### ISSUE TITLE
[newrelic-infrastructure] cannot set enable process metrics to false

### ISSUE THREAD

**Issue by davidbrota** [newrelic/helm-charts#285]
**Bug description**

The enableProcessMetrics lets you configure whether the infrastructure agent should send or not send process metrics ( https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/configuration/infrastructure-agent-configuration-settings#enable-process-metrics
). Accounts created before July 20, 2020 have this config option enabled by default. Therefore, they need to be able to set the value to false, otherwise the default value changes based on the account creation date. Currently, the chart only allows setting enableProcessMetrics's value to true, assuming that the default value is always false, which is not the case.

**Which chart?**

helm chart version: newrelic-infrastructure-2.0.2

**What happened?**

After setting enableProcessMetrics to false, customer was still receiving process data. 

**What you expected to happen?**

Customer shouldn't receive any process data

**Comment by paologallinaharbur** [comment]
Hello, it is an issue with the helm template that is not able to recognize the difference between the logical false, 0 and nil.

There are two workaround, the first one is to pass the bool as a string:

```yaml 
enableProcessMetrics: "false"
```
```bash 
$ helm template ./charts/newrelic-infrastructure -f ./values.yaml | grep "PROCESS" -C2
            - name: "NRIA_ENABLE_PROCESS_METRICS"
              value: "false"
```

The second one is to pass the value with the agent config file and is mounted and mapped in the container


---

A proper fix would be to  include` enableProcessMetrics: "false"` in the values since we specify in the documentation that it is disabled by default

**Comment by davidbrota** [comment]
Great! option one looks good to me, whereas option two seems too hacky and prone to errors.

**Comment by paologallinaharbur** [comment]
I'll add in the values, that commented out to keep the current behaviour, but making it easier to configure for the users
