### ISSUE TITLE
[newrelic-infrastructure] Increase sampling rate to reduce storage cost

### ISSUE THREAD

**Issue by kakarot291994** [newrelic/helm-charts#374]
Hi We are trying to increase the sample rate in newrelic bundle and new relic infrastructure chart but as per the official chart documentation there are no configuration parameters for setting up: - 

metrices_storage_sample_rate and metrices_network_storage_sample_rate .

Please let us know how we could increase the value for those as we are need to increase sample rate to decrease the cost.

**Comment by paologallinaharbur** [comment]
@mangulonr

**Comment by paologallinaharbur** [comment]
Related to https://github.com/newrelic/nri-kubernetes/issues/83

It is currently not possible, however this is in our roadmap, unfortunately I do not have yet an ETA yet.

**Comment by paologallinaharbur** [comment]
It is currently in our roadmap for Q3

**Comment by nmehlei** [comment]
@paologallinaharbur Hey Paolo, since Q3 already ended, would you mind giving us an update on where on the roadmap this issue currently resides? Thanks!

**Comment by roobre** [comment]
Hi there,

Just wanted to comment that version 3 of the newrelic integration has been released, which among [many other things](https://docs.newrelic.com/docs/kubernetes-pixie/kubernetes-integration/get-started/changes-since-v3/) it also allows changing the scrape interval.

Please feel free to take a look at the changes and give it a try! To do so, it is enough to run your typical `helm` command with the `--devel` flag to put the latest version, which is currently in beta: `helm upgrade newrelic/nri-bundle [...] --devel`.

Please let us know if this works for you!
