### ISSUE TITLE
[nri-metadata-injection] Update apiVersion: admissionregistration.k8s.io

### ISSUE THREAD

**Issue by denismatiu** [newrelic/helm-charts#444]
**Bug description**
Unable to install chart in cluster version higher than 1.19

```
  kubernetes:admissionregistration.k8s.io/v1beta1:MutatingWebhookConfiguration (newrelic/newrelic-metadata-injection-nri-metadata-injection):
    error: apiVersion "admissionregistration.k8s.io/v1beta1/MutatingWebhookConfiguration" was removed in Kubernetes 1.19. Use "admissionregistration.k8s.io/v1/MutatingWebhookConfiguration" instead.
```

 See https://git.k8s.io/kubernetes/CHANGELOG/CHANGELOG-1.19.md#deprecation-1 for more information.

**Version of Helm and Kubernetes**
```
helm Version:"v3.5.4"
k8s version   1.19.10-gke.1600
```

**Which chart?**
```
    chart: "nri-metadata-injection",
    version: "1.5.1",
```
**What happened?**

```
  kubernetes:admissionregistration.k8s.io/v1beta1:MutatingWebhookConfiguration (newrelic/newrelic-metadata-injection-nri-metadata-injection):
    error: apiVersion "admissionregistration.k8s.io/v1beta1/MutatingWebhookConfiguration" was removed in Kubernetes 1.19. Use "admissionregistration.k8s.io/v1/MutatingWebhookConfiguration" instead.
```
**What you expected to happen?**

**How to reproduce it?**

Install  the chart to a k8s cluster version higher than 1.19

**Anything else we need to know?**

https://github.com/newrelic/helm-charts/blob/nri-metadata-injection-1.5.1/charts/nri-metadata-injection/templates/admission-webhooks/mutatingWebhookConfiguration.yaml#L1

Should be replaced with   `apiVersion: admissionregistration.k8s.io/v1`

**Comment by paologallinaharbur** [comment]
related to https://github.com/newrelic/helm-charts/issues/304

**Comment by paologallinaharbur** [comment]
Hi @denismatiu , can you give us more information about the kind of cluster your are using (self managed, Azure, EKS...) ? 
admissionregistration.k8s.io/v1beta1 is supposed to be removed in 1.22 only: kubernetes/kubernetes#82021 (comment)

We tested it already up to 1.21 and we never faced any issue apart from warnings as shown in the related issue. Also those warnings specifies that the v1beta1 is removed since 1.22 on

**Comment by paologallinaharbur** [comment]
Possibly related https://github.com/elastic/cloud-on-k8s/issues/3958

**Comment by denismatiu** [comment]
Hi @paologallinaharbur 
I am using google GKE `  1.19.10-gke.1600`

**Comment by paologallinaharbur** [comment]
Yes, but I do not understand why they are removed already: the gke docs as well states that this is going to happen in 1.22:

![Screen Shot 2021-07-30 at 5 07 07 PM](https://user-images.githubusercontent.com/43335750/127673306-0da68d8f-c3c6-4982-a2ee-02c68850ad8c.png)
https://cloud.google.com/kubernetes-engine/docs/release-notes

**Comment by paologallinaharbur** [comment]
Can you share full log/command you are running?

**Comment by Embraser01** [comment]
Hi, I stumbled on the same issue while using Pulumi. Looks like it was an issue with them that was fix on latest versions:

- Where the check is done: https://github.com/pulumi/pulumi-kubernetes/blob/master/provider/pkg/kinds/deprecated.go#L51
- The PR that pospone the removal https://github.com/pulumi/pulumi-kubernetes/pull/1474

For me the fix was to manually edit the state of each stack to upgrade the provider to latest version.

**Comment by paologallinaharbur** [comment]
Closing for now for inactivity, let us now if you are still facing any issue
