### ISSUE TITLE
[newrelic-logging] Add ability to specify custom attributes and parsers

### ISSUE THREAD

**Issue by WilliamABradley** [newrelic/helm-charts#75]
**Is your feature request related to a problem? Please describe.**

I would like to be able to add additional custom attributes to logs sent to NewRelic Logs within the helm chart. It would also be nice to specify custom parsers from within the helm chart.

**Describe the solution you'd like**

This could be added by using an `logs.customAttributes` map for the chart variables, that would create records at:

https://github.com/newrelic/helm-charts/blob/6fe37ccb4bd84f8f913819951108b2aecfb2cdb5/charts/newrelic-logging/templates/configmap.yaml#L34-L38

Much like the cluster_name custom attribute, added by default.

So, for example, if we wanted to add some location info about the cluster, e.g. Cloud, Region, etc.

```.conf
[FILTER]
    Name record_modifier
    Match *
    Record cluster_name ${CLUSTER_NAME}
    Record cloud aws
    Record cloud_region ap-southeast-2
```

**Describe alternatives you've considered**

Patch the ConfigMap separately, this isn't easy when using Infrastructure as Code, e.g. Terraform, which is what we are using.

**Additional context**

**Comment by jsubirat** [comment]
Hi @WilliamABradley , many thanks for your feature request. We'll evaluate it and get back to you. I'm currently moving all the pending issues from our soon-to-be-deprecated [kubernetes-logging repository](https://github.com/newrelic/kubernetes-logging). I assume that this ticket is a replica of [this one](https://github.com/newrelic/kubernetes-logging/issues/31). Please let me know if that's not the case. Thank you very much in advance.

**Comment by jsubirat** [comment]
Hi @WilliamABradley , a new feature has been added to add additional attributes in this PR: https://github.com/newrelic/helm-charts/pull/609

You can now achieve it with the following config in `values.yml`:
```
fluentBit:
  config:
    extraFilters: |
      # Include any custom attributes in the FILTER below
      [FILTER]
          Name            record_modifier
          Match           *
          Record          customAttributeName1 customAttributeValue1
          Record          customAttributeName2 customAttributeValue2
```

With regards to the ability to specify additional parsers, could you please describe what would be the use case you'd be targeting? Normally, your logs would follow either the docker or the cri format. If you would like to _then_ parse them as, say, `nginx` logs, you'd need to define a [parser filter](https://docs.fluentbit.io/manual/pipeline/filters/parser) to intercept only the logs coming from an Nginx pod, and then apply that parser to them. But to do this, you'd need to rewrite its tag first so that only the Nginx logs are intercepted by this filter.
