### ISSUE TITLE
[newrelic-infrastructure-v3] KSM Horizontal Pod Autoscaling metrics are missing

### ISSUE THREAD

**Issue by pragmaticivan** [newrelic/helm-charts#765]
**Bug description**

KSM HPA metrics are missing. Dashboards are not created and Metrics are not available. Making it required to maintain a separated KSM just for that.

**Version of Helm and Kubernetes**
Helm 3
Kubernetes 1.21

**Which chart?**

newrelic-infrastructure-v3 - v3.1.0

**What happened?**

The documentation says HPA metrics are available in the previous chart but in the v3 it got dropped somehow.

**What you expected to happen?**

Metrics and Dashboards are available in NewRelic.

**How to reproduce it?**

1. Install chart with v3.
2. Verify that metric is not being generated.

**Comment by davidgit** [comment]
Hi @pragmaticivan,

Just to be sure, a couple of questions: 

1. Which KSM version are you using? 
2. Do you have more than one KSM instance?

David.

**Comment by pragmaticivan** [comment]
@davidgit I'm referring to the KSM used by v3 of this helm chart. I'm using the latest version of the v3 chart.

**Comment by pragmaticivan** [comment]
@davidgit we do have our own KSM ingesting into a Prometheus cluster, but it's unrelated at this point (I think).

**Comment by pragmaticivan** [comment]
Hi @davidgit do you need any new input?

**Comment by paologallinaharbur** [comment]
Hello! Just to recap.

 - you updated the version of the nri-kubernetes chart to v3 and you are not seeing anymore HPA metrics.
Just to be clear you are referring to these metrics -> [HPAsample](https://docs.newrelic.com/docs/kubernetes-pixie/kubernetes-integration/understand-use-data/find-use-your-kubernetes-data#hpa-data)
 
If my understanding is correct, it is not an expected behaviour and it is either a bug or a misconfiguration (In our canaries and our tests did not spot any issue):
 - Which version or KSM are you running in your cluster? Supported version is 1.9.8
 - Do you have multiple KSM versions in your cluster? The integration could autodiscover different ksm installations and use them by mistake
 - Can you share verbose logs of the ksm component?

Notice that the integration leverages [kube-state-metrics version 1.9.8](https://github.com/kubernetes/kube-state-metrics) that is automatically installed by the nri-bundle (if enabled). 
Since KSM 2.x breaks HPA metrics it is possible that the integration is scraping by mistake a 2.x KSM instance

**Comment by pragmaticivan** [comment]
> Hello! Just to recap.
> 
> * you updated the version of the nri-kubernetes chart to v3 and you are not seeing anymore HPA metrics.
>   Just to be clear you are referring to these metrics -> [HPAsample](https://docs.newrelic.com/docs/kubernetes-pixie/kubernetes-integration/understand-use-data/find-use-your-kubernetes-data#hpa-data)
> 
> If my understanding is correct, it is not an expected behaviour and it is either a bug or a misconfiguration (In our canaries and our tests did not spot any issue):
> 
> * Which version or KSM are you running in your cluster? Supported version is 1.9.8
> * Do you have multiple KSM versions in your cluster? The integration could autodiscover different ksm installations and use them by mistake
> * Can you share verbose logs of the ksm component?
> 
> Notice that the integration leverages [kube-state-metrics version 1.9.8](https://github.com/kubernetes/kube-state-metrics) that is automatically installed by the nri-bundle (if enabled). Since KSM 2.x breaks HPA metrics it is possible that the integration is scraping by mistake a 2.x KSM instance

We're using `kube-state-metrics:v2.4.1` from prometheus operator. I will try to get some verbose logs soon.

**Comment by pragmaticivan** [comment]
FYI, I disabled KSM in one of our clusters and that metric still does not show up.

**Comment by roobre** [comment]
Hi,

Our integration consumes HPA metrics from KSM. As a result of a change that was made in the name and format of HPA metrics in KSM v2, our integration will not be able to retrieve HPA metrics from KSM v2.

Normally, this is not a problem as we include a version of KSM that wors for us in the `nri-bundle` chart, `1.9.8`. This should work fine in most scenarios. However, if you do have an additional instance of KSM in the cluster, with a non compatible version, our integration _may_ pick it up instead of the one that is bundled. This might sound a bit weird, but we do that to keep defaults reasonable for people who want to bring their own KSM.

Fortunately, this can be workarounded by changing:
1. Changing the label selector the integration uses to find a KSM instance here:
https://github.com/newrelic/nri-kubernetes/blob/825d7b31d2aff2a4f9cb06c9ace5e834acc587ed/charts/newrelic-infrastructure/values.yaml#L150
1. Changing the labels attached to either the 1.9.8 instance of KSM, or the 2.4.1 one, in such a way that only the 1.9.8 instance is matched by the labelSelector above

By doing this, the integration should pick the correct version for it and you should be able to see the metric as a result.

In the meantime, adding support for KSM 2.x is in our roadmap so we hope this to stop being a problem soon :)

**Comment by pragmaticivan** [comment]
@roobre just tried the approach by using both label and namespace. Metric still doesn't show up ;/ I think it's picking the right version now but still don't see that SampleBeing Created

![Screen Shot 2022-05-09 at 12 18 14 PM](https://user-images.githubusercontent.com/301291/167463021-dca310cb-5262-483b-8761-38b863293e8e.png)

**Comment by maxlemieux** [comment]
If the [bundle chart](https://github.com/newrelic/helm-charts/blob/master/charts/nri-bundle/Chart.yaml) isn't used, the [KSM v1.9.8 chart](https://kubernetes.github.io/kube-state-metrics/) won't be pulled in as a dependency automatically. This can be added for standalone `newrelic-infrastructure` chart installations with:

```
helm repo add kube-state-metrics https://kubernetes.github.io/kube-state-metrics
helm install -n newrelic kube-state-metrics kube-state-metrics/kube-state-metrics
```

**Comment by pragmaticivan** [comment]
@maxlemieux I actually have KSM running from the new chart, and that's indeed available from the Values.yaml config https://github.com/newrelic/nri-kubernetes/blob/main/charts/newrelic-infrastructure/values.yaml#L102 maybe it's coming from somewhere else?

**Comment by pragmaticivan** [comment]
KSM config:
```yaml
ksm:
  tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
  resources:
    limits:
      cpu: 200m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 512Mi
  config:
    selector: "app.kubernetes.io/name=newrelic-infrastructure"
    namespace: "kube-system"
```

**Comment by pragmaticivan** [comment]
Maybe I got confused by this container that is also called `ksm`:

```
  Containers:
   ksm:
    Image:      newrelic/nri-kubernetes:3.1.0
    Environment:
      NRI_KUBERNETES_SINK_HTTP_PORT:  8002
      NRI_KUBERNETES_CLUSTERNAME:     _redacted_
      NRI_KUBERNETES_VERBOSE:         false
      NRI_KUBERNETES_NODENAME:         (v1:spec.nodeName)
    Mounts:
     _redacted_
```
 
Ref: `kubectl describe deploy/newrelic-infrastructure-_redacted_-ksm`

**Comment by davidgit** [comment]
Hi , 

The next best step is to visit [New Relic Support](https://support.newrelic.com/), where you can engage the New Relic Support Community or open a support ticket depending on your support level. The support team is best positioned to assist with your specific needs. 

Please provide a link to this GitHub issue when submitting your community post or support ticket.

Thanks!
