### ISSUE TITLE
[nri-bundle] What is release 4.3.2?

### ISSUE THREAD

**Issue by guhcampos** [newrelic/helm-charts#808]
I noticed some of my automated processes tried to upgrade the chart version of NRI Bundle from `3.6.2` to `4.3.2` which seemed like a huge increase, specially given there was never a `4.0.0`. I cannot be sure, but it seems like a mistake? Possibly a typo for a `3.4.2` release since the `3.4.1` is the latest from that branch?

Fortunatelly I have guardrails around major version bumps, so I was not really impacted in any way, but other customers may not be so lucky, so I figured it would be worth to report it.

**Comment by hndrewaall** [comment]
Got hit by this. Moreover, rolling back is a pain, since it seems there is now a missing secret:

```
Rollback "newrelic-bundle" failed: no Secret with the name "newrelic-bundle-newrelic-infrastructure-config" found 
```

**Comment by kang-makes** [comment]
Hi @guhcampos,

There was a notice and a public beta.

Here you have the docs about what changed with the release of `nri-kubernetes` v3: https://docs.newrelic.com/docs/kubernetes-pixie/kubernetes-integration/get-started/changes-since-v3/

And here you can see all the previous versions that we released as beta: https://github.com/newrelic/helm-charts/blob/gh-pages/index.yaml#L4823

**Comment by kang-makes** [comment]
Hi @hndrewaall,

It is a shame, to be honest. Helm removes previous objects that were created by the chart while upgrading and is not able to recreate them.

You will have to template the chart manually and create that secret by hand.

**Comment by kang-makes** [comment]
The release is correct so I am closing this issue.

If you have any doubt just let me know.
